spring:
  jackson:
    date-format: yyyy.MM.dd HH:mm:ss
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

  datasource:
    url: jdbc:mysql://localhost:3306/mega_board?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
logging:
  charset:
    console: UTF-8
  level:
    dev.full: DEBUG
    org.springframework.security: INFO


